# Generated by Django 2.2.1 on 2019-05-09 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cotravelling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertrip',
            unique_together={('user', 'trip')},
        ),
    ]
