# Generated by Django 2.2.1 on 2019-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotravelling', '0002_auto_20190509_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
