# Generated by Django 2.2.1 on 2019-05-09 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotravelling', '0003_usertrip_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.date(2019, 5, 10)),
        ),
    ]
