# Generated by Django 2.2.1 on 2019-05-09 22:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cotravelling', '0004_auto_20190510_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 9, 22, 30, 51, 580079, tzinfo=utc)),
        ),
    ]
