# Generated by Django 2.2.1 on 2019-05-09 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cotravelling', '0005_auto_20190510_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.TimeField(default=datetime.datetime(2019, 5, 9, 22, 33, 53, 995441, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 5, 9, 22, 33, 53, 995386, tzinfo=utc)),
        ),
    ]
