# Generated by Django 2.2.1 on 2019-05-09 22:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotravelling', '0006_auto_20190510_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trip',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
