# Generated by Django 2.2.1 on 2019-05-12 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotravelling', '0007_auto_20190510_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
        migrations.AddField(
            model_name='trip',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
